Repository Proxima-Project/Proxi-Bay12, pull requests merged in 2022-07, with the labels that each got.

#191 Обновление шаблона для ПР
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Приоритетно, Внутреннее

#194 Better ranks
  maps/torch/icons/mob/onmob_accessories_solgov.dmi
  maps/torch/icons/obj/obj_accessories_solgov.dmi
  maps/torch/items/clothing/solgov-accessory.dm
Labels: Нововведение, Изображения, Обновить-Вики

#187 SFP Moment
  code/modules/clothing/under/accessories/badges.dm
  maps/torch/job/command_jobs.dm
  maps/torch/job/exploration_jobs.dm
  maps/torch/job/outfits/security_outfits.dm
  maps/torch/job/security_jobs.dm
  maps/torch/torch5_deck1.dmm
  maps/torch/torch_ranks.dm
Labels: Нововведение, Лор, Обновить-Вики

#204 менее кривая иконка паркура
  icons/mob/screen1_Midnight.dmi
  icons/mob/screen1_Orange.dmi
  icons/mob/screen1_White.dmi
Labels: Sprites

#207 Рай Корп ЧВК
  baystation12.dme
  code/__defines/guns.dm
  proxima/code/game/items/weapons/projectile/infinity-ammuntion.dm
  proxima/code/game/items/weapons/projectile/infinity-guns.dm
  proxima/code/game/items/weapons/projectile/infinity-projectiles.dm
  proxima/icons/mob/onmob/lefthand.dmi
  proxima/icons/mob/onmob/righthand.dmi
  proxima/icons/obj/guns/ammo.dmi
  proxima/icons/obj/guns/guns.dmi
Labels: Нововведение, Порт, Внутреннее, Sprites

#210 Изменение в системе гостевых пропусков (№2)
  code/game/machinery/computer/guestpass.dm
Labels: Ошибки
