Repository Proxima-Project/Proxi-Bay12, pull requests merged in 2022-08, with the labels that each got.

#211 Каст о чки
  baystation12.dme
  customs/code/lodagn.dm
  customs/code/vezha.dm
  customs/config/lodagn-coat.json
  customs/config/vezha-hat.json
  customs/icons/mob/custom_items_mob.dmi
  customs/icons/obj/custom_items_obj.dmi
Labels: Sprites

#213 Новые спрайты
  maps/torch/icons/mob/onmob_under_solgov.dmi
Labels: Нововведение, Изображения, Sprites

#215 Новый язык для планеты "Лорриман" - Лирис!
  baystation12.dme
  code/__defines/languages.dm
  code/modules/culture_descriptor/location/locations_human.dm
  code/modules/integrated_electronics/subtypes/input.dm
  code/modules/mob/language/human/arabic.dm
  code/modules/mob/language/human/chinese.dm
  code/modules/mob/language/human/euro.dm
  code/modules/mob/language/human/indian.dm
  code/modules/mob/language/human/lirris.dm
  code/modules/mob/language/human/misc/gutter.dm
  code/modules/mob/language/human/misc/spacer.dm
  code/modules/mob/language/human/russian.dm
  code/modules/mob/language/human/selenian.dm
  code/modules/mob/language/human/spanish.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/silicon/pai/software_modules.dm
  code/modules/mob/living/silicon/robot/modules/_module.dm
  code/stylesheet.dm
Labels: Нововведение

#208 Добавление плащей для отделов, новых балаклав для людей и новых военных курточек для гражданских!
  baystation12.dme
  code/modules/clothing/spacesuits/spacesuits.dm
  maps/torch/loadout/loadout_accessories.dm
  maps/torch/loadout/loadout_head.dm
  maps/torch/loadout/loadout_suit.dm
  proxima/code/modules/clothing/accessories/cloak.dm
  proxima/code/modules/clothing/masks/masks.dm
  proxima/code/modules/clothing/suits/suits.dm
  proxima/icons/mob/onmob/onmob_accessories.dmi
  proxima/icons/mob/onmob/onmob_suit.dmi
  proxima/icons/obj/clothing/obj_accessories.dmi
  proxima/icons/obj/clothing/obj_suit.dmi
Labels: Нововведение, Порт, Изображения, Sprites

#218 Изменение в списке возможных печатаемых предметов автолатом
  code/game/objects/items/devices/binoculars.dm
  code/game/objects/items/weapons/mop.dm
  code/modules/fabrication/designs/general/designs_general.dm
Labels: Нововведение

#219 Невероятные изменения в сборке и где они обитают?
  code/datums/supplypacks/galley.dm
  code/datums/supplypacks/operations.dm
  code/datums/supplypacks/security.dm
  code/game/machinery/teleporter/console.dm
  code/game/objects/items/weapons/storage/boxes.dm
  maps/torch/datums/supplypacks/security.dm
Labels: Нововведение, Внутреннее

#220 Ох мой бог
  code/game/verbs/emotions.dm
  code/modules/emotes/definitions/visible.dm
Labels: Ошибки
