Repository Proxima-Project/Proxi-Bay12, pull requests merged in 2022-06, with the labels that each got.

#155 Исправление отдачи тяжёлой снайперской винтовки
  code/modules/projectiles/guns/projectile/sniper.dm
Labels: Ошибки

#156 Горки и бду. Часть 2.
  baystation12.dme
  code/modules/client/preference_setup/loadout/lists/tactical.dm
  proxima/code/modules/clothing/under/under.dm
  proxima/icons/mob/onmob/mob_acs.dmi
  proxima/icons/mob/onmob/mob_suit.dmi
  proxima/icons/mob/onmob/mob_uni.dmi
  proxima/icons/obj/clothing/icon_acs.dmi
  proxima/icons/obj/clothing/icon_suit.dmi
  proxima/icons/obj/clothing/icon_uni.dmi
Labels: Ошибки, Нововведение, Временно, Изображения

#161 Восстановление работы модифицированного револьвера .zakatneba#8715
  customs/code/zakatneba.dm
  customs/icons/obj/custom_items_obj.dmi
Labels: Ошибки, Внутреннее

#149 Триумфальное возвращение ИИ.
  baystation12.dme
  code/__defines/ai_ui.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/silicon/ai/ai_camera_proc.dm
  maps/torch/job/command_jobs.dm
  maps/torch/job/misc_jobs.dm
  maps/torch/job/torch_jobs.dm
  maps/torch/torch3_deck3.dmm
  maps/torch/torch4_deck2.dmm
  maps/torch/torch6_bridge.dmm
  maps/torch/torch_areas.dm
  maps/torch/torch_unit_testing.dm
  proxima/code/_helpers/_onclick/hud/_defines_ai.dm
  proxima/code/_helpers/_onclick/hud/ai_hud.dm
  proxima/code/_helpers/_onclick/hud/ai_screen_object.dm
  proxima/code/modules/silicon/ai/ai.dm
  proxima/code/modules/silicon/ai/procs.dm
  proxima/icons/mob/screen_ai.dmi
  proxima/sound/AI/attention.ogg
  proxima/sound/AI/newai.ogg
Labels: Нововведение, Порт, Карта

#163 ёгурт
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Внутреннее

#162 Фиксы ИИ, а ещё и карты!!
  baystation12.dme
  code/game/machinery/ai_slipper.dm
  maps/torch/torch2_deck4.dmm
  maps/torch/torch3_deck3.dmm
  maps/torch/torch5_deck1.dmm
  maps/torch/torch6_bridge.dmm
  proxima/icons/obj/machinery/ai_slipper.dmi
Labels: Ошибки, Карта

#150 Спонсирование уменьшено, поэтому получайте более дешёвое снаряжение
  proxima/code/modules/clothing/suit/suit.dm
  proxima/icons/mob/onmob/mob-acs.dmi
  proxima/icons/mob/onmob/mob-suit.dmi
  proxima/icons/mob/onmob/mob-uni.dmi
  proxima/icons/obj/clothing/icon-acs.dmi
  proxima/icons/obj/clothing/icon-suit.dmi
  proxima/icons/obj/clothing/icon-uni.dmi
Labels: Нововведение, Временно, Внутреннее, Изображения

#132 Dawn of Synthetics
  code/__defines/mobs.dm
  code/modules/client/preference_setup/loadout/lists/xenowear.dm
  code/modules/clothing/spacesuits/rig/suits/combat.dm
  code/modules/clothing/spacesuits/rig/suits/ert.dm
  code/modules/clothing/spacesuits/rig/suits/light.dm
  code/modules/clothing/spacesuits/rig/suits/merc.dm
  code/modules/clothing/spacesuits/rig/suits/station.dm
  code/modules/clothing/suits/labcoat.dm
  code/modules/emotes/definitions/audible.dm
  code/modules/mob/living/carbon/human/descriptors/_descriptors.dm
  code/modules/mob/living/carbon/human/descriptors/descriptors_generic.dm
  code/modules/mob/mob.dm
  code/modules/species/shell/shell.dm
  code/modules/species/species_getters.dm
  code/modules/species/station/machine.dm
  maps/torch/datums/shackle_law_sets.dm
  maps/torch/items/cards_ids.dm
  maps/torch/items/clothing/solgov-accessory.dm
  maps/torch/items/encryption_keys.dm
  maps/torch/items/headsets.dm
  maps/torch/items/machinery.dm
  maps/torch/items/rigs.dm
  maps/torch/job/corporate_jobs.dm
  maps/torch/job/engineering_jobs.dm
  maps/torch/job/outfits/corporate_outfits.dm
  maps/torch/job/torch_jobs.dm
  maps/torch/loadout/_defines.dm
  maps/torch/structures/closets/command.dm
  maps/torch/torch4_deck2.dmm
  maps/torch/torch5_deck1.dmm
  maps/torch/torch_antagonism.dm
  maps/torch/torch_areas.dm
  maps/torch/torch_ranks.dm
Labels: Ошибки, Нововведение, Карта

#185 Marine Force
  code/__defines/culture.dm
  code/modules/client/preference_setup/loadout/lists/tactical.dm
  code/modules/client/preference_setup/loadout/lists/utility.dm
  code/modules/clothing/clothing_forensics.dm
  code/modules/culture_descriptor/faction/factions_human.dm
  maps/torch/datums/uniforms_army.dm
  maps/torch/icons/mob/onmob_suit_solgov.dmi
  maps/torch/icons/obj/obj_suit_solgov.dmi
  maps/torch/items/clothing/solgov-accessory.dm
  maps/torch/items/clothing/solgov-head.dm
  maps/torch/items/clothing/solgov-suit.dm
  maps/torch/job/engineering_jobs.dm
  maps/torch/job/exploration_jobs.dm
  maps/torch/job/medical_jobs.dm
  maps/torch/job/outfits/command_outfits.dm
  maps/torch/job/outfits/engineering_outfits.dm
  maps/torch/job/outfits/exploration_outfits.dm
  maps/torch/job/outfits/medical_outfits.dm
  maps/torch/job/outfits/security_outfits.dm
  maps/torch/job/outfits/service_outfits.dm
  maps/torch/job/outfits/supply_outfits.dm
  maps/torch/job/outfits/unused_outfits.dm
  maps/torch/job/security_jobs.dm
  maps/torch/job/service_jobs.dm
  maps/torch/job/supply_jobs.dm
  maps/torch/job/torch_jobs.dm
  maps/torch/loadout/loadout_accessories.dm
  maps/torch/loadout/loadout_head.dm
  maps/torch/loadout/loadout_suit.dm
  maps/torch/torch_ranks.dm
Labels: Нововведение, Лор, Обновить-Вики
