Repository Proxima-Project/Proxi-Bay12, pull requests merged in 2023-01, with the labels that each got.

#245 Ух ты перевод
  code/__defines/culture.dm
  code/modules/client/preference_setup/occupation/occupation.dm
  code/modules/culture_descriptor/culture/cultures_human.dm
  code/modules/culture_descriptor/faction/factions_human.dm
  code/modules/culture_descriptor/faction/factions_ipc.dm
  code/modules/culture_descriptor/faction/factions_skrell.dm
  code/modules/culture_descriptor/faction/factions_unathi.dm
  code/modules/culture_descriptor/faction/factions_vox.dm
  code/modules/culture_descriptor/location/locations_adherent.dm
  code/modules/culture_descriptor/location/locations_diona.dm
  code/modules/culture_descriptor/location/locations_human.dm
  code/modules/culture_descriptor/location/locations_ipc.dm
  code/modules/culture_descriptor/location/locations_other.dm
  code/modules/culture_descriptor/location/locations_serpentids.dm
  code/modules/culture_descriptor/location/locations_skrell.dm
  code/modules/culture_descriptor/location/locations_unathi.dm
  code/modules/culture_descriptor/location/locations_vox.dm
  code/modules/culture_descriptor/religion/religions_human.dm
  code/modules/culture_descriptor/religion/religions_skrell.dm
  code/modules/culture_descriptor/religion/religions_unathi.dm
  code/modules/culture_descriptor/religion/religions_vox.dm
  maps/torch/job/command_jobs.dm
  maps/torch/job/corporate_jobs.dm
  maps/torch/job/engineering_jobs.dm
  maps/torch/job/exploration_jobs.dm
  maps/torch/job/medical_jobs.dm
  maps/torch/job/misc_jobs.dm
  maps/torch/job/research_jobs.dm
  maps/torch/job/security_jobs.dm
  maps/torch/job/service_jobs.dm
  maps/torch/job/supply_jobs.dm
  maps/~mapsystem/maps.dm
Labels: Внутреннее

#244 Емодзи
  code/modules/emoji/emoji_parse.dm
  icons/emoji.dmi
Labels: Ошибки, Нововведение, Внутреннее, Изображения

#243 Перевод или ошибка? [Исправь это - эдишен]
  baystation12.dme
  code/__defines/culture.dm
  code/game/objects/random/random.dm
  code/modules/client/preferences_spawnpoints.dm
  code/modules/clothing/under/accessories/stethoscope.dm
  code/modules/culture_descriptor/culture/cultures_adherent.dm
  code/modules/culture_descriptor/culture/cultures_diona.dm
  code/modules/culture_descriptor/culture/cultures_ipc.dm
  code/modules/culture_descriptor/culture/cultures_serpentid.dm
  code/modules/culture_descriptor/culture/cultures_skrell.dm
  code/modules/culture_descriptor/culture/cultures_unathi.dm
  code/modules/culture_descriptor/culture/cultures_vox.dm
  code/modules/emoji/emoji_parse.dm
  code/modules/species/shell/shell.dm
  code/modules/species/station/machine.dm
  proxima/code/game/objects/items/toys.dm
  proxima/code/modules/silicon/ai/ai.dm
  proxima/icons/obj/toys.dmi
  sound/AI/a-newAI.ogg
  sound/AI/newAI.ogg
Labels: Ошибки, Нововведение, Порт, Приоритетно, Лор, Внутреннее

#247 обновление горячей картошки
  baystation12.dme
  code/datums/supplypacks/security.dm
  code/datums/uplink/ammunition.dm
  code/datums/uplink/grenades.dm
  code/game/objects/items/weapons/storage/boxes.dm
  code/game/objects/structures/crates_lockers/closets/_closet_appearance_definitions.dm
  code/game/objects/structures/crates_lockers/closets/utility_closets.dm
  code/modules/power/cell.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/projectiles/guns/energy/nuclear.dm
  code/modules/projectiles/guns/energy/pulse.dm
  code/modules/projectiles/guns/energy/secure.dm
  code/modules/projectiles/guns/energy/special.dm
  code/modules/projectiles/guns/energy/stun.dm
  code/modules/projectiles/guns/energy/vox.dm
  code/modules/projectiles/guns/guncell.dm
  maps/antag_spawn/ert/ert_base.dmm
  maps/torch/datums/supplypacks/security.dm
  maps/torch/loadout/loadout_accessories.dm
  maps/torch/structures/closets/exploration.dm
  maps/torch/structures/closets/misc.dm
  maps/torch/torch5_deck1.dmm
  proxima/code/game/items/weapons/gun/energy/k342.dm
  proxima/icons/obj/guns/guncells.dmi
Labels: Нововведение, Внутреннее
